In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Hotel_Dataset.csv")
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [3]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
dtype: bool

In [4]:
df = df.drop_duplicates()
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [5]:
len(df)

10

In [6]:
index = np.array(list(range(0, len(df))))
df = df.set_index(index)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       10 non-null     int64
 1   Age_Group        10 non-null     str
 2   Rating(1-5)      10 non-null     int64
 3   Hotel            10 non-null     str
 4   FoodPreference   10 non-null     str
 5   Bill             10 non-null     int64
 6   NoOfPax          10 non-null     int64
 7   EstimatedSalary  10 non-null     int64
 8   Age_Group.1      10 non-null     str
dtypes: int64(5), str(4)
memory usage: 1.0 KB

In [8]:
df = df.drop(columns=['Age_Group.1'])
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777

In [9]:
df.loc[df['CustomerID'] < 0, 'CustomerID'] = np.nan

df.loc[df['Bill'] < 0, 'Bill'] = np.nan

df.loc[df['EstimatedSalary'] < 0, 'EstimatedSalary'] = np.nan

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,veg,1300.0,2,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2,120000.0
4,5.0,35+,3,Ibis,Vegetarian,989.0,2,45000.0
5,6.0,35+,3,Ibys,Non-Veg,1909.0,2,122220.0
6,7.0,35+,4,RedFox,Vegetarian,1000.0,-1,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,-10,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3,NaN
9,10.0,30-35,5,RedFox,non-Veg,NaN,4,87777.0

In [10]:
df.loc[
    (df['NoOfPax'] < 1) | (df['NoOfPax'] > 20),
    'NoOfPax'
] = np.nan

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Vegetarian,989.0,2.0,45000.0
5,6.0,35+,3,Ibys,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,NaN
9,10.0,30-35,5,RedFox,non-Veg,NaN,4.0,87777.0

In [11]:
df['Age_Group'].unique()

<ArrowStringArray>
['20-25', '30-35', '25-30', '35+']
Length: 4, dtype: str

In [12]:
df['Hotel'].unique()

<ArrowStringArray>
['Ibis', 'LemonTree', 'RedFox', 'Ibys']
Length: 4, dtype: str

In [13]:
df['Hotel'] = df['Hotel'].replace('Ibys', 'Ibis')
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Vegetarian,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,NaN
9,10.0,30-35,5,RedFox,non-Veg,NaN,4.0,87777.0

In [14]:
df['FoodPreference'].unique()

<ArrowStringArray>
['veg', 'Non-Veg', 'Veg', 'Vegetarian', 'non-Veg']
Length: 5, dtype: str

In [15]:
df['FoodPreference'] = df['FoodPreference'].replace({
    'veg': 'Veg',
    'Vegetarian': 'Veg',
    'non-Veg': 'Non-Veg'
})

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,NaN,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,NaN
9,10.0,30-35,5,RedFox,Non-Veg,NaN,4.0,87777.0

In [16]:
df['FoodPreference'].unique()

<ArrowStringArray>
['Veg', 'Non-Veg']
Length: 2, dtype: str

In [17]:
df['EstimatedSalary'] = df['EstimatedSalary'].fillna(
    round(df['EstimatedSalary'].mean())
)

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,NaN,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,96755.0
9,10.0,30-35,5,RedFox,Non-Veg,NaN,4.0,87777.0

In [18]:
df['NoOfPax'] = df['NoOfPax'].fillna(
    round(df['NoOfPax'].median())
)

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,2.0,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,2.0,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,96755.0
9,10.0,30-35,5,RedFox,Non-Veg,NaN,4.0,87777.0

In [19]:
df['Rating(1-5)'] = df['Rating(1-5)'].fillna(
    round(df['Rating(1-5)'].median())
)

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,2.0,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,2.0,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,96755.0
9,10.0,30-35,5,RedFox,Non-Veg,NaN,4.0,87777.0

In [20]:
df['Bill'] = df['Bill'].fillna(
    round(df['Bill'].mean())
)

df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,2.0,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,2.0,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,96755.0
9,10.0,30-35,5,RedFox,Non-Veg,1801.0,4.0,87777.0

In [21]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,2.0,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,2.0,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,96755.0
9,10.0,30-35,5,RedFox,Non-Veg,1801.0,4.0,87777.0